### Technique to perform Feature transformation
- Normalizations
- Standardization
- Log Transformations
- Robust scaler
- Max absolute scaler

In [9]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
from sklearn.preprocessing import StandardScaler, _encoders ,MaxAbsScaler, MinMaxScaler, RobustScaler, MinMaxScaler

# Normalization / min max scaler

In [10]:
df = pd.read_csv('estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition.csv')

In [11]:
df.head()

,Height,Weight,family_history_with_overweight,SCC,MTRANS_Walking,FAVC_z,FCVC_minmax,NCP_z,CAEC_minmax,CH2O_minmax,FAF_minmax,TUE_z,CALC_z,Age_bin_minmax,NObeyesdad
0,1.62,64.0,1,0,0,2.766876,0.5,0.404704,0.333333,0.5,0.000000,0.550985,1.439033,0.25,1
1,1.52,56.0,1,1,0,2.766876,1.0,0.404704,0.333333,1.0,1.000000,1.092724,0.516552,0.25,1
2,1.80,77.0,1,0,0,2.766876,0.5,0.404704,0.333333,0.5,0.666667,0.550985,2.472136,0.50,1
3,1.80,87.0,0,0,1,2.766876,1.0,0.404704,0.333333,0.5,0.666667,1.092724,2.472136,0.75,2
4,1.78,89.8,0,0,0,2.766876,0.5,2.164116,0.333333,0.5,0.000000,1.092724,0.516552,0.50,3

In [12]:
df.columns

Index(['Height', 'Weight', 'family_history_with_overweight', 'SCC',
       'MTRANS_Walking', 'FAVC_z', 'FCVC_minmax', 'NCP_z', 'CAEC_minmax',
       'CH2O_minmax', 'FAF_minmax', 'TUE_z', 'CALC_z', 'Age_bin_minmax',
       'NObeyesdad'],
      dtype='object')

[Link](https://prnt.sc/V-S9_AWUZzgY)

In [13]:
df.rename(columns={
    'family_history_with_overweight': 'weight_history',
    'SCC': 'Sugar_Cons',
    'MTRANS_Walking': 'transport_walking',
    'FAVC_z': 'heigh_caloric_food',
    'FCVC_minmax': 'Vegetable_cons'
}, inplace=True)

In [14]:
df.head()

,Height,Weight,weight_history,Sugar_Cons,transport_walking,heigh_caloric_food,Vegetable_cons,NCP_z,CAEC_minmax,CH2O_minmax,FAF_minmax,TUE_z,CALC_z,Age_bin_minmax,NObeyesdad
0,1.62,64.0,1,0,0,2.766876,0.5,0.404704,0.333333,0.5,0.000000,0.550985,1.439033,0.25,1
1,1.52,56.0,1,1,0,2.766876,1.0,0.404704,0.333333,1.0,1.000000,1.092724,0.516552,0.25,1
2,1.80,77.0,1,0,0,2.766876,0.5,0.404704,0.333333,0.5,0.666667,0.550985,2.472136,0.50,1
3,1.80,87.0,0,0,1,2.766876,1.0,0.404704,0.333333,0.5,0.666667,1.092724,2.472136,0.75,2
4,1.78,89.8,0,0,0,2.766876,0.5,2.164116,0.333333,0.5,0.000000,1.092724,0.516552,0.50,3