# Techniques to perform Feature Transformation:
1. Normalization <br>
2. Standardization <br>
3. Log Transformation <br>
4. Robust Scaler <br>
5. Max Absolute Scaler

In [43]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler, PowerTransformer, FunctionTransformer
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Wine_Data.csv')

In [3]:
df.head()

,Unnamed: 0,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
0,0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [4]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [5]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [6]:
df.tail()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64
dtypes: float64(11), int64(2)
memory usage: 18.2 KB

In [8]:
df.describe()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [9]:
df.isnull().sum()

Alcohol                 0
Malic_Acid              0
Ash                     0
Ash_Alcanity            0
Magnesium               0
Total_Phenols           0
Flavanoids              0
Nonflavanoid_Phenols    0
Proanthocyanins         0
Color_Intensity         0
Hue                     0
OD280                   0
Proline                 0
dtype: int64

In [10]:
df.shape

(178, 13)

### Normalization / min max scaler

In [11]:
max_alcohol = df.Alcohol.max()
min_alcohol = df.Alcohol.min()

In [12]:
max_alcohol

14.83

In [13]:
min_alcohol

11.03

In [14]:
df['Alcohol_norm_manual'] = (df.Alcohol - min_alcohol ) / (max_alcohol - min_alcohol)

In [15]:
df.filter(like='Alcohol')

     Alcohol  Alcohol_norm_manual
0      14.23             0.842105
1      13.20             0.571053
2      13.16             0.560526
3      14.37             0.878947
4      13.24             0.581579
..       ...                  ...
173    13.71             0.705263
174    13.40             0.623684
175    13.27             0.589474
176    13.17             0.563158
177    14.13             0.815789

[178 rows x 2 columns]

In [16]:
df['Alcohol']

0      14.23
1      13.20
2      13.16
3      14.37
4      13.24
       ...
173    13.71
174    13.40
175    13.27
176    13.17
177    14.13
Name: Alcohol, Length: 178, dtype: float64

# Now calculate normalization using sklearn

In [17]:
mmx = MinMaxScaler()

In [18]:
df['alcohol_norm_sklearn'] = mmx.fit_transform(df[['Alcohol']])

In [19]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Alcohol_norm_manual,alcohol_norm_sklearn
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0.842105,0.842105
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0.571053,0.571053
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0.560526,0.560526
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0.878947,0.878947
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.581579,0.581579

# 2.Standardization

Manually calculation

In [20]:
mean_alcohol = df.Alcohol.mean()
std = df.Alcohol.std()

In [21]:
df['alcohol_std_manually'] = (df['Alcohol'] - mean_alcohol) / std

In [22]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Alcohol_norm_manual,alcohol_norm_sklearn,alcohol_std_manually
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0.842105,0.842105,1.514341
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0.571053,0.571053,0.245597
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0.560526,0.560526,0.196325
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0.878947,0.878947,1.686791
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.581579,0.581579,0.294868

Standardization using sklearn

In [23]:
scaler = StandardScaler()

In [24]:
df['alcohol_std_sklearn'] = scaler.fit_transform(df[['Alcohol']])

In [25]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Alcohol_norm_manual,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0.842105,0.842105,1.514341,1.518613
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0.571053,0.571053,0.245597,0.246290
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0.560526,0.560526,0.196325,0.196879
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0.878947,0.878947,1.686791,1.691550
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.581579,0.581579,0.294868,0.295700

### Robust Scaler (outliers)

In [26]:
robust = RobustScaler()

In [27]:
df['robust_alcohol'] = robust.fit_transform(df[['Alcohol']])

In [28]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Alcohol_norm_manual,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn,robust_alcohol
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0.842105,0.842105,1.514341,1.518613,0.897338
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0.571053,0.571053,0.245597,0.246290,0.114068
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0.560526,0.560526,0.196325,0.196879,0.083650
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0.878947,0.878947,1.686791,1.691550,1.003802
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.581579,0.581579,0.294868,0.295700,0.144487

# Max Absolute Scaler

manually calculate

In [29]:
max_abs = df.Alcohol.max()

In [30]:
df['max_abs_manually'] = df.Alcohol / max_abs

In [31]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Alcohol_norm_manual,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn,robust_alcohol,max_abs_manually
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0.842105,0.842105,1.514341,1.518613,0.897338,0.959541
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0.571053,0.571053,0.245597,0.246290,0.114068,0.890088
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0.560526,0.560526,0.196325,0.196879,0.083650,0.887390
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0.878947,0.878947,1.686791,1.691550,1.003802,0.968982
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.581579,0.581579,0.294868,0.295700,0.144487,0.892785

Using sklearn

In [32]:
mabs = MaxAbsScaler()

In [33]:
df['max_abs_alcohol'] = mabs.fit_transform(df[['Alcohol']])

In [34]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Alcohol_norm_manual,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn,robust_alcohol,max_abs_manually,max_abs_alcohol
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,0.842105,0.842105,1.514341,1.518613,0.897338,0.959541,0.959541
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,0.571053,0.571053,0.245597,0.246290,0.114068,0.890088,0.890088
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,0.560526,0.560526,0.196325,0.196879,0.083650,0.887390,0.887390
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,0.878947,0.878947,1.686791,1.691550,1.003802,0.968982,0.968982
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0.581579,0.581579,0.294868,0.295700,0.144487,0.892785,0.892785

# Log Transformation

In [45]:
fc = FunctionTransformer(np.log1p)
df['alcohol_fc'] = fc.fit_transform(df[['Alcohol']])

In [46]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,...,Alcohol_norm_manual,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn,robust_alcohol,max_abs_manually,max_abs_alcohol,Alcohol_log,box cox,alcohol_fc
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,...,0.842105,0.842105,1.514341,1.518613,0.897338,0.959541,0.959541,1.182700,25.561379,2.723267
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,...,0.571053,0.571053,0.245597,0.246290,0.114068,0.890088,0.890088,1.152288,23.276202,2.653242
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,...,0.560526,0.560526,0.196325,0.196879,0.083650,0.887390,0.887390,1.151063,23.188423,2.650421
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,...,0.878947,0.878947,1.686791,1.691550,1.003802,0.968982,0.968982,1.186674,25.875608,2.732418
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,...,0.581579,0.581579,0.294868,0.295700,0.144487,0.892785,0.892785,1.153510,23.364055,2.656055

In [47]:
df['fc_np'] = np.log1p(df[['Alcohol']]) # Another way

In [48]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,...,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn,robust_alcohol,max_abs_manually,max_abs_alcohol,Alcohol_log,box cox,alcohol_fc,fc_np
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,...,0.842105,1.514341,1.518613,0.897338,0.959541,0.959541,1.182700,25.561379,2.723267,2.723267
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,...,0.571053,0.245597,0.246290,0.114068,0.890088,0.890088,1.152288,23.276202,2.653242,2.653242
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,...,0.560526,0.196325,0.196879,0.083650,0.887390,0.887390,1.151063,23.188423,2.650421,2.650421
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,...,0.878947,1.686791,1.691550,1.003802,0.968982,0.968982,1.186674,25.875608,2.732418,2.732418
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,...,0.581579,0.294868,0.295700,0.144487,0.892785,0.892785,1.153510,23.364055,2.656055,2.656055

# Power Transformar

In [49]:
log = PowerTransformer()
df['Alcohol_log'] = log.fit_transform(df[['Alcohol']])

In [50]:
df['Alcohol_log'] = log.fit_transform(df[['Alcohol']])

In [51]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,...,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn,robust_alcohol,max_abs_manually,max_abs_alcohol,Alcohol_log,box cox,alcohol_fc,fc_np
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,...,0.842105,1.514341,1.518613,0.897338,0.959541,0.959541,1.530388,25.561379,2.723267,2.723267
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,...,0.571053,0.245597,0.246290,0.114068,0.890088,0.890088,0.238381,23.276202,2.653242,2.653242
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,...,0.560526,0.196325,0.196879,0.083650,0.887390,0.887390,0.188751,23.188423,2.650421,2.650421
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,...,0.878947,1.686791,1.691550,1.003802,0.968982,0.968982,1.708049,25.875608,2.732418,2.732418
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,...,0.581579,0.294868,0.295700,0.144487,0.892785,0.892785,0.288052,23.364055,2.656055,2.656055

### Power Transformer (box cox)

In [52]:
from scipy.stats import boxcox

In [53]:
df['box cox'], _ = boxcox(df['Alcohol'] + 1) #data,param

In [54]:
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,...,alcohol_norm_sklearn,alcohol_std_manually,alcohol_std_sklearn,robust_alcohol,max_abs_manually,max_abs_alcohol,Alcohol_log,box cox,alcohol_fc,fc_np
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,...,0.842105,1.514341,1.518613,0.897338,0.959541,0.959541,1.530388,25.561379,2.723267,2.723267
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,...,0.571053,0.245597,0.246290,0.114068,0.890088,0.890088,0.238381,23.276202,2.653242,2.653242
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,...,0.560526,0.196325,0.196879,0.083650,0.887390,0.887390,0.188751,23.188423,2.650421,2.650421
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,...,0.878947,1.686791,1.691550,1.003802,0.968982,0.968982,1.708049,25.875608,2.732418,2.732418
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,...,0.581579,0.294868,0.295700,0.144487,0.892785,0.892785,0.288052,23.364055,2.656055,2.656055

In [55]:
df['Alcohol_log'] = np.log(df['Alcohol'] + 1) 
df['Alcohol_log'] = np.log10(df['Alcohol'] + 1)  # Logarithm base 10